### ISSUE TITLE
Questions about window size settings

### ISSUE THREAD

**Issue by zhengkunxiong** [Yale-LILY/DYLE#10]
Hi, thanks for your outstanding work!
I noticed that when preprocessing data for the generator, the length of the content of a turn of conversations is determined by the window_size and max_source_len. You set the window size to 0, which means that the content of the conversation is limited to the sentence itself, without any contextual information (assuming that the sentence contains less than the maximum length of words). 
May I ask what is the reason for setting the window size to 0? Is completing some contextual information not beneficial in terms of performance。

**Comment by MaoZiming** [comment]
Hi, thank you for the interest! The main reason is that adding neighboring text for the generator tokenizer does not bring significant performance improvement. Also, sometimes the input snippets (e.g. dialogue turns) can be already quite long which requires us to raise the max_source_len (more GPU memory needed).
