### ISSUE TITLE
CUDA out of memory.

### ISSUE THREAD

**Issue by Hanlian1** [Yale-LILY/DYLE#11]
Thanks for your outstanding work!

When I was training your model, I encountered an out-of-memory issue. I am using a Tesla V100S 32G GPU, and although I tried reducing the batch size to 1, the problem still persists. Is there any way to reduce the memory consumption during training?

**Comment by ChenWu98** [comment]
Hi, thanks for your interest! We run all experiments on one RTX 8000 GPU with 48g memory. A lowered number of extracted snippets will help, but it may harm the performance since less information is seen by the generator.
