### ISSUE TITLE
Problems in code (attention mask is not used)

### ISSUE THREAD

**Issue by PaperPlane7** [Yale-LILY/DYLE#12]
![image](https://github.com/Yale-LILY/DYLE/assets/34757313/c56edca0-73dd-4698-9a0f-febccf7631a5)
The first question: multiple sentences form chunk input roberta, but the attention mask part of the sentence is 0, and the part of the [sep] token is 1, will this cause the model to lose sight of the sentence?

![image](https://github.com/Yale-LILY/DYLE/assets/34757313/d76e4598-3247-45e9-90e9-240cc0f7dab2)
Did it make a difference if you didn't use the Attention Mask when you trained Roberta?

**Comment by ChenWu98** [comment]
Hi! I believe that the global attention mask is not used in the final model. Sorry about the confusion!

**Comment by PaperPlane7** [comment]
> Hi! I believe that the global attention mask is not used in the final model. Sorry about the confusion!

If you don't use the global attention mask, will the [pad] token affect the model calculation?

**Comment by ChenWu98** [comment]
I don’t think it’s hard for the model to learn to ignore the pad tokens.

**Comment by PaperPlane7** [comment]
> I don’t think it’s hard for the model to learn to ignore the pad tokens.

Ok I see, thanks for the reply！
