### ISSUE TITLE
Minimum GPU requirement

### ISSUE THREAD

**Issue by mayankjobanputra** [Yale-LILY/DYLE#2]
I was wondering what's the minimum amount of VRAM is required even to test the models? also for training? I have 2 16 GB cards but I couldn't make it work even with batch size 1.

**Comment by phamkhactu** [comment]
@mayankjobanputra Have you fixed it?? I have same problem?

**Comment by ChenWu98** [comment]
Hi @mayankjobanputra  @phamkhactu, DYLE unmodified will not fit on 2 x 16GB cards. We run on one RTX 8000 GPU with 48g memory. We have not tested A100 with 40g memory, but a larger card or a lowered number of extracted snippets will always help!
