### ISSUE TITLE
About dynamic weight and irrelevant snippets

### ISSUE THREAD

**Issue by RIU-13** [Yale-LILY/DYLE#3]
Hello, I have read your paper and I am trying to run your code. You say this model can denoise by down-weighting irrelevant snippets but I can't find this filtering in your code. So how does it recogonize irrelevant snippets？By scoring similarity？

**Comment by RIU-13** [comment]
And are you sure that the Arxiv dataset's website is right? It doesn't contain articles. May this website is correct?https://huggingface.co/datasets/scientific_papers
Looking forward to your reply ~

**Comment by MaoZiming** [comment]
Hi, I noticed we put the wrong link for the Arxiv dataset. 
This is the correct one: https://huggingface.co/datasets/scientific_papers
Thanks for pointing it out!

**Comment by MaoZiming** [comment]
We don't use explicit filtering for downweighting irrelelvant snippets. The proposed consistency loss helps the extractor pick out more relevant snippets and downweighting irrelevant ones
