### ISSUE TITLE
About oracles of arxiv

### ISSUE THREAD

**Issue by RIU-13** [Yale-LILY/DYLE#4]
Hello, sorry to bother you. I have difficulty in processing oracles of arxiv training set. I just run arxiv_oracle.py and wait. I trained for 4 days and it only produces 4300 files in index_train.  Can you check this python files? I'm really confused now.

**Comment by RIU-13** [comment]
I‘ve find the problem.

**Comment by RIU-13** [comment]
The progress takes me 100% MEM, it may have some problems.....

**Comment by RIU-13** [comment]
How long did it take you to run this program？

**Comment by MaoZiming** [comment]
Hi, @RIU-13, it is somewhat slow (I believe 3-4 days) and we used more workers (and correspondingly more cpu cores) on our cluster. How much memory do you have on your server?
