### ISSUE TITLE
About the method of learning rate decay

### ISSUE THREAD

**Issue by RIU-13** [Yale-LILY/DYLE#6]
Hello! Sorry to bother you again. In Experiment.py, it writes "no_improvement = self.seq_evaluate_gen(test=False, beam_size=beam_size)" and " if no_improvement and self.iter_num > config.start_decay:" to achieve learning rate decay. But self.seq_evaluate_gen doesn't return anything, personally I set the "no_improvement = True" if the evaluation rouge scores don't improve, which means if "metric > self.best_metric", then "no_improvement = False". Am I right? 
I am trying to achieve the expected scores mentioned in your paper, but my scores are much lower and it doesn't improve much in training iteration.

**Comment by RIU-13** [comment]
My GPU is 3090Ti

**Comment by MaoZiming** [comment]
I think you are right, it was likely a mistake and there was no learning rate decay.

**Comment by therookieprogrammer** [comment]
> Hello! Sorry to bother you again. In Experiment.py, it writes "no_improvement = self.seq_evaluate_gen(test=False, beam_size=beam_size)" and " if no_improvement and self.iter_num > config.start_decay:" to achieve learning rate decay. But self.seq_evaluate_gen doesn't return anything, personally I set the "no_improvement = True" if the evaluation rouge scores don't improve, which means if "metric > self.best_metric", then "no_improvement = False". Am I right? I am trying to achieve the expected scores mentioned in your paper, but my scores are much lower and it doesn't improve much in training iteration.

Sorry to bother you, but have you achieved the results of your paper after correcting the code?
