### ISSUE TITLE
Does the validation and test need oracle?The code cannot match the paper

### ISSUE THREAD

**Issue by RIU-13** [Yale-LILY/DYLE#7]
In your code, you write that only during train and test need oracle. But in your paper, you say "No extractive oracles are used
during test time".

**Comment by MaoZiming** [comment]
Oracle is only used during training.

**Comment by therookieprogrammer** [comment]
> In your code, you write that only during train and test need oracle. But in your paper, you say "No extractive oracles are used during test time".

can you achieve the results in this paper?
