### ISSUE TITLE
not achieve the results

### ISSUE THREAD

**Issue by therookieprogrammer** [Yale-LILY/DYLE#8]
Thank you for your outstanding work, but when I downloaded the qmsum checkpoint you provided, I did not achieve the results of my paper on my server, which was 1-2 points lower than the results in the paper. May I ask what the reason is? The server is 3080

**Comment by therookieprogrammer** [comment]
Is the checkpoint you gave the best?

**Comment by MaoZiming** [comment]
@therookieprogrammer Hi, thank you for your interest. We were able to reproduce the results the last time we tried. May I ask what Rouge package you are using?

**Comment by therookieprogrammer** [comment]
> @therookieprogrammer Hi, thank you for your interest. We were able to reproduce the results the last time we tried. May I ask what Rouge package you are using?

Thank you for your reply. For convenience, I only used the "route. get_scores (preds, refs, avg=True)" function in the Rouge package to calculate the scores. I did not use the "rouge_with_pyrouge (preds, refs)" function in the original code to calculate. May I ask if there is a problem with the way to calculate the rouge score?

**Comment by MaoZiming** [comment]
I think different rouge packages have different ways of tokenization/normalization, which may affect rouge scores to some degree. We used the official Perl script of ROUGE-1.5.5. Not sure if that is the reason for the difference.

**Comment by therookieprogrammer** [comment]
I also downloaded the govreport checkpoint to run the test set, but the score of rouge1 is 10 points lower than that of the paper. Will the calculation difference between different rouge packages be so large?

**Comment by MaoZiming** [comment]
Hmm, I am not sure why. The difference should not be this big. Unfortunately, we don't have access to the server and other checkpoints for now; is it possible for you to run the training on GovReport? I remember the current config should work

**Comment by zhengkunxiong** [comment]
This issue is indeed caused by using different versions of rouge. This will result in different data preprocessing and final evaluation stage from the source code process
